### ISSUE TITLE
npm install fails on Arch - but is resolvable

### ISSUE THREAD

**Issue by RMKD** [lightning-viz/lightning#52]
steps taken
- installed libsass with pacman (arch package manager)
- reinstalled node-sass
- attempted npm install (failed)
- changed dependency to node-sass 3.2.0 and re-installed
- attempted npm install (failed)
- removed ./node_modules
- ran npm install from scratch (success!)

log
```
>npm install

> lightning-server@0.2.1 postinstall ~/tools/lightning
> npm run build && npm run fetch-visualizations


> lightning-server@0.2.1 build ~/tools/lightning
> gulp build

~/tools/lightning/node_modules/gulp-sass/node_modules/node-sass/sass.js:22
  throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?
        ^
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at requireBinding (~/tools/lightning/node_modules/gulp-sass/node_modules/node-sass/sass.js:22:9)
    at Object.<anonymous> (~/tools/lightning/node_modules/gulp-sass/node_modules/node-sass/sass.js:25:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (~/tools/lightning/node_modules/gulp-sass/index.js:3:13)
    at Module._compile (module.js:460:26)

npm ERR! Linux 4.1.6-1-MANJARO
npm ERR! argv "node" "~/tools/lightning/node_modules/.bin/npm" "run" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! lightning-server@0.2.1 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lightning-server@0.2.1 build script 'gulp build'.
npm ERR! This is most likely a problem with the lightning-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls lightning-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/tools/lightning/npm-debug.log

npm ERR! Linux 4.1.6-1-MANJARO
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE
npm ERR! lightning-server@0.2.1 postinstall: `npm run build && npm run fetch-visualizations`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lightning-server@0.2.1 postinstall script 'npm run build && npm run fetch-visualizations'.
npm ERR! This is most likely a problem with the lightning-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run fetch-visualizations
npm ERR! You can get their info via:
npm ERR!     npm owner ls lightning-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/tools/lightning/npm-debug.log
```

**Comment by mathisonian** [comment]
@RMKD 

I've seen this error happen after people upgrade `node` versions, and the solution has been to remove `node_modules` folder completely and reinstall. Did you happen to recently upgrade? 

You ultimately had success with `node-sass` `3.2.0` or `2.1.1`?
