### ISSUE TITLE
npm start fails with missing favicon

### ISSUE THREAD

**Issue by npyoung** [lightning-viz/lightning#57]
Installing and running lightning server from source.

Ubuntu 14.04
node v0.12.7
npm 2.11.3

```npm start``` after successful install gives
```
fs.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy

Error: ENOENT, no such file or directory '/root/code/lightning/public/images/favicon.ico'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at favicon (/root/code/lightning/node_modules/serve-favicon/index.js:64:15)
    at module.exports (/root/code/lightning/config/express.js:36:13)
    at Object.<anonymous> (/root/code/lightning/server.js:41:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by npyoung** [comment]
This turned out to be a permissions issue. npm attempts to run at a lower permissions level, which creates problems if you are running npm commands as root. Adding `--unsafe-perm` fixes this. Now I'm just seeing #56.

**Comment by rashmithajajur** [comment]
Where did you add --unsafe-perm?

**Comment by npyoung** [comment]
In the start command i.e. `npm start --unsafe-perm`

**Comment by rashmithajajur** [comment]
Hi @npyoung I tried npm start --unsafe-perm command also...still its not getting app.css file to my local host.
