### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by bmweiner** [lightning-viz/lightning#59]
I am trying to run a local server using Node on a Windows 8.1 machine. I can start the server with `lightning-server`, but there is an error thrown, when I try to view a session with a visualization:

    $ uname
    MINGW64_NT-6.3
    $ pwd
    /c/Users/name
    $ lightning-server
    Lightning started on port: 3000
    Error: Cannot find module 'lightning-line' from 'C:\Users\name'
        at C:\Users\name\AppData\Roaming\npm\node_modules\lightning-server\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
        at process (C:\Users\name\AppData\Roaming\npm\node_modules\lightning-server\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
        at ondir (C:\Users\name\AppData\Roaming\npm\node_modules\lightning-server\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
        at load (C:\Users\name\AppData\Roaming\npm\node_modules\lightning-server\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
        at onex (C:\Users\name\AppData\Roaming\npm\node_modules\lightning-server\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
        at C:\Users\name\AppData\Roaming\npm\node_modules\lightning-server\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
        at FSReqWrap.oncomplete (fs.js:82:15)

It appears that the module call is failing because it's looking in the current working directory rather than my *node_modules* directory.

If I run `lightning-server` from my npm folder, no errors are thrown (viz displays as expected).

    alias lightning-server='cd $(cygpath $APPDATA/npm) && lightning-server'

Does lightning rely on any Node/NPM configs? I have node and npm on my path, but no environment variables set.

**Comment by mathisonian** [comment]
hey @bmweiner,

lightning uses browserify under the hood to dynamically compile some modules. it looks like thats where things are breaking down.

browserify gets its path set [here](https://github.com/lightning-viz/lightning/blob/master/app/controllers/static.js#L35-L37) based on [this config property](https://github.com/lightning-viz/lightning/blob/master/config/config.js#L42).

what it should be doing is setting `config.root` to the directory wherever lighting was installed (in this case `C:\Users\name\AppData\Roaming\npm\node_modules\lightning-server`. 

It looks like something wacky is happening with the paths on windows. i primarily dev on osx and linux, any help finding a solution is appreciated

**Comment by dazebug** [comment]
I had similar problem here.
I'm on the Ubuntu 14.04.4 LTS.

```bash
> lightning-server
Lightning started on port: 3000
Error: Cannot find module 'lightning-line' from '/home/username'
    at /home/username/.nvm/versions/node/v4.2.3/lib/node_modules/lightning-server/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/home/username/.nvm/versions/node/v4.2.3/lib/node_modules/lightning-server/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/username/.nvm/versions/node/v4.2.3/lib/node_modules/lightning-server/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/home/username/.nvm/versions/node/v4.2.3/lib/node_modules/lightning-server/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/username/.nvm/versions/node/v4.2.3/lib/node_modules/lightning-server/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/username/.nvm/versions/node/v4.2.3/lib/node_modules/lightning-server/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

In this case, should I do same wacky trick you said before? @mathisonian

**Comment by mathisonian** [comment]
Hey @dazebug what version of `lightning-server` do you have installed?
